### ISSUE TITLE
内部リンクに移動しない

### ISSUE THREAD

**Issue by querykuma** [increments/qiita-discussions#176]
内部リンクのある記事において下書きでテストをしたら移動しませんでした。小文字に変換されるのが原因だと思います。

`### HTML5の廃止について調べよう`があるとき内部リンク`[HTML5の廃止について調べよう](#HTML5の廃止について調べよう)`において下書きで内部リンクに移動しませんでした。

HTMLが次のように変換されていました。

```
<h3>
<span id="html5の廃止について調べよう" class="fragment">
HTML5の廃止について調べよう</h3>
```

公開後のHTMLがどうなるかはまだ試していません。

**Comment by kyntk** [comment]
@querykuma ご報告いただきありがとうございます!

お調べいただいた通り、見出しへ移動しないのは見出しに付与されるidが小文字となっているからです！
こちらは公開後も同様となっております。 

そのため、`[HTML5の廃止について調べよう](#html5の廃止について調べよう)` としていただければ対象の見出し位置まで移動させることができるので、お試しください :pray:

また、Qiita DiscussionsではIssueではなく、Discussionを用いたディスカッションを行っています ！
次回ご意見をいただける際は、以下のリンクを参考にDiscussionをご利用ください :bow:
https://github.com/increments/qiita-discussions/discussions/116
