### ISSUE TITLE
コメント欄のLGTMボタンと数字の間隔が狭い

### ISSUE THREAD

**Issue by tanaka-asami415** [increments/qiita-discussions#224]
### Discussed in https://github.com/increments/qiita-discussions/discussions/222

<div type='discussions-op-text'>

<sup>Originally posted by **JunichiIto** May 14, 2022</sup>
コメント欄のLGTMボタンと、その右に表示されている数字の間隔がほとんど無いように見えます。

<img width="353" alt="Screen Shot 2022-05-14 at 7 26 47" src="https://user-images.githubusercontent.com/1148320/168397057-16294c32-6ee2-4fa3-9566-f24da2c7eae5.png">

多少間を空けた方が良いと思うのですがいかがでしょうか？

<img width="218" alt="Screen Shot 2022-05-14 at 7 29 20" src="https://user-images.githubusercontent.com/1148320/168397140-1315adc3-3fa5-4dc0-89ba-487b74241523.png">

上記の例は[こちらのコメント](https://qiita.com/kubochiro/items/557ad6276b106ab9180b#comment-a86c1885aa1376e84d9f)のスクショです。</div>

**Comment by kyntk** [comment]
LGTMボタンと数字との間に隙間ができるように変更しました
![](https://user-images.githubusercontent.com/17251829/171550327-2493b7bd-e83a-41aa-9cd6-da451f397841.png)
