### ISSUE TITLE
ストック機能を改善する

### ISSUE THREAD

**Issue by xrxoxcxox** [increments/qiita-discussions#229]
## 概要

- ストックをしやすくするために、ストックするためのステップを減らす
    - https://github.com/increments/qiita-discussions/discussions/114
- ストック一覧ページのカテゴリー表示数を増やす
    - https://github.com/increments/qiita-discussions/discussions/65
    - > カテゴリーの数が多い場合省略表示され何回も「もっと見る」を押さなければならないので、そちらも初期表示数を多くするなどするといいかもしれません。

## 期待される効果

- ストックをしやすくなる
- ストックした記事を管理、検索しやすくなる
- など

## どのように使うか

現在細かな改善案は未定なので、決まり次第記載します。

## その他ご意見をいただいたもの

これらはすぐに対応とはならないですが、近い将来に改善することを検討しています。

- https://github.com/increments/qiita-discussions/discussions/65
- https://github.com/increments/qiita-discussions/discussions/199
- https://github.com/increments/qiita-discussions/discussions/59
- https://github.com/increments/qiita-discussions/discussions/112
- https://github.com/increments/qiita-discussions/discussions/435

対応済みのもの

- [x] https://github.com/increments/qiita-discussions/discussions/27
- [x] https://github.com/increments/qiita-discussions/discussions/227

**Comment by Sheephuman** [comment]
ここでいいのかな？
フォントサイズ設定次第の事象だが、Stockでカテゴリ登録したものが10を超えると「保存」が見切れるようになった。ページ全体のフォントサイズを縮めれば出るようにはなるが。マイナーで恐縮だがFirefox使ってる。

追記。スクールバーはサイト本体とストック内の両方ともスクロールしても見切れたまま

![image](https://user-images.githubusercontent.com/34499259/229304267-3f1b766f-1d9c-4e88-87a7-641c25f278fa.png)

**Comment by kyntk** [comment]
@Sheephuman 返信が遅くなり申し訳ございません :bow: 
内容を確認して修正をいたします。

また、今後こういった不具合の報告の際は、Discussionsへお送りいただけますと幸いです！
https://github.com/increments/qiita-discussions/discussions

**Comment by kyntk** [comment]
ストックが1アクションでできるようになりました ✨
ぜひお試しください！
https://twitter.com/Qiita/status/1666410919025586178

ストックされるカテゴリーとしては、まずはデフォルトで「あとで読む」にストックされるようになっています。
今後の改善として、ユーザーごとにデフォルトカテゴリーを選択できるようにすることも検討しています！

**Comment by wataru86** [comment]
ストック一覧ページのサイドバーに表示されるカテゴリーのデフォルト数が10になりました :rocket:
https://qiita.com/release-notes/2023-06-14
