### ISSUE TITLE
タグをミュートできる機能を追加する

### ISSUE THREAD

**Issue by xrxoxcxox** [increments/qiita-discussions#253]
## 概要

現在実装されているユーザーのミュートと同様、特定のタグをミュートできる機能を実装する。

## 期待される効果

- 各種フィードに、自分の見たくないタグの記事が流れてこなくなる
- 代わりに他の記事が表示されるので、より興味のある記事に出会える可能性が高まる

## どのように使うか

該当のタグページにミュート用ボタンのようなものを追加予定で、そちらを実行していただきます。
基本的な使用方法や挙動はユーザーミュートと同じになる予定です。

## 関連

- https://github.com/increments/qiita-discussions/discussions/158

**Comment by kyntk** [comment]
リリースしたため close
https://blog.qiita.com/release-tag-mute-general/
