### ISSUE TITLE
折りたたみにマウスカーソルをホバーしてもカーソルのスタイルが変わらない

### ISSUE THREAD

**Issue by tanaka-asami415** [increments/qiita-discussions#290]
### Discussed in https://github.com/increments/qiita-discussions/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **Yarakashi-Kikohshi** September  1, 2022</sup>

`<details>` タグと `<summary>` タグを利用して折りたたみを作成することが出来ますが、ここにマウスカーソルをホバーしてもスタイルが変わりません。このため、折りたたみを知らない人が読んだ際、折りたたみに気付けない可能性があります。

折りたたみをホバーした際にも、マウスカーソルが以下の赤丸ような指 :point_up_2: になると良いと思います。

![qiitaMouseSymbol](https://user-images.githubusercontent.com/75878492/187739056-a4c42de7-a140-411e-9d08-ac9a0d7b990a.png)

### 現在のマウスカーソルの様子

![qiitaDetails](https://user-images.githubusercontent.com/75878492/187739060-22f01819-971e-418e-86c5-2ba8dd9ba93c.gif)
</div>

**Comment by wataru86** [comment]
対応が完了したため Close します。

https://github.com/increments/qiita-discussions/discussions/289#discussioncomment-3748898
