### ISSUE TITLE
エディタの埋め込み要素のちらつきをなくす

### ISSUE THREAD

**Issue by wataru86** [increments/qiita-discussions#440]
# 概要

現在、記事や質問のエディタにおいて、ツイート等の埋め込み要素が存在する場合に、以下動画のように1文字打つたびに埋め込み要素がちらついてしまいます。

https://user-images.githubusercontent.com/34445284/221823594-3c0ec555-73c2-436b-b656-33d4e142d4f6.mov

# 期待される効果

ちらつきが発生しなくなり、記事の執筆が快適になる予定です。

# どのように使うか

ユーザーの皆さまに設定いただく内容はありません。
機能自体の変更もないため、ベータ版リリースを挟まず、記事と質問のエディタから順に適用していきます。

**Comment by xrxoxcxox** [comment]
[リリースノート](https://qiita.com/release-notes/2023-03-14)でお知らせした通り、改善しましたのでクローズします！
