### ISSUE TITLE
ダークモード対応

### ISSUE THREAD

**Issue by xrxoxcxox** [increments/qiita-discussions#446]
## 概要

現在QiitaにはダークモードのUIが存在しないため、新たに作成します。

## 期待される効果

- 画面全体の輝度が下がり、目に優しくなる
- 夜間など暗い環境において見やすくなる
- 見た目が格好良くなる

## どのように使うか

ベータ版公開を挟んだ後、正式公開を予定しています。
ベータ版の時期は以下のブログの手順で適用いただけます。

https://blog.qiita.com/article-page-dark-mode-beta/

正式公開後は、OS設定やユーザー設定などからライトモードとダークモードを切り替えられるようにする予定です。
（仕様は変更になる可能性があります。）

**Comment by tanaka-asami415** [comment]
## 下記ページの対応を行いました

- 記事ページ（2月15日）
- 各種フィードページ（3月10日）
- ユーザーページ、タグページ（4月6日）
- 質問ページ（4月18日）

**Comment by tanaka-asami415** [comment]
## ダークモードを正式版としてリリースしました

正式版では、モードの切替を行えるよう「テーマカラー設定」機能を追加しました！

詳細は下記ブログをご参照ください！✨
https://blog.qiita.com/release-theme/
