### ISSUE TITLE
エディタのスタイリングのアップデート

### ISSUE THREAD

**Issue by xrxoxcxox** [increments/qiita-discussions#453]
## 概要

エディタのスタイリングのアップデートを実施します。
機能そのものの追加・削除は無く、見た目の変更のみを予定しています。

## 期待される効果

- エディタのレイアウトやトーンの変更により、サイト全体でのスタイルが統一される
- エディタの横幅に最大値を持たせることで大きなディスプレイでも使用しやすくなる
- 画像や絵文字の挿入、同時スクロールのオンオフなど、アクション類がまとまって配置され、使用しやすくなる

## どのように使うか

ベータ版公開を挟んだ後、正式公開を予定しています。
正式公開後は特別な設定は不要です。

**Comment by kyntk** [comment]
## 以下の対応を行いました

- 2023/3/28 エディタのデザイン変更をベータ版として公開しました
    - https://blog.qiita.com/editor-design-update-beta/
- 2023/4/18 エディタのスタイリングのアップデートを実施しました
    - https://blog.qiita.com/editor-design-update/

今後も引き続き改善を予定しています :sparkles:

**Comment by getty104** [comment]
- 2023/7/11 エディタのアップデートを行いました
    - https://qiita.com/release-notes/2023-07-11

こちらで一旦このIssueはクローズとします！
