### ISSUE TITLE
mermaidJSのバージョンアップ（現在 mermaid version 8.14.0）

### ISSUE THREAD

**Issue by xrxoxcxox** [increments/qiita-discussions#476]
### Discussed in https://github.com/increments/qiita-discussions/discussions/475

<div type='discussions-op-text'>

<sup>Originally posted by **SakakitaniJunya** May 15, 2023</sup>
mermaidJSのバージョンアップ希望しています。
mermaidJSは、10系までリリースされていて、8系ではtimelineなどのグラフが作成できません。
QiitaのmermaidJS（現在 mermaid version 8.14.0）</div>

**Comment by tanaka-asami415** [comment]
Mermaidのバージョンアップを行ったためクローズ
https://qiita.com/release-notes/2023-07-26
