### ISSUE TITLE
ローカルで記事の執筆・プレビュー・投稿ができるツール

### ISSUE THREAD

**Issue by kyntk** [increments/qiita-discussions#482]
## 概要

手元の環境で記事の執筆・プレビュー・投稿ができるツールを開発しています。
これを使うことで、普段ご自身で使っているツールを使って記事の執筆・投稿がしやすくなります。

詳しい内容は[Qiita Blog](https://blog.qiita.com/qiita-cli-beta-release/)をご確認ください。

## 期待される効果

Qiitaではより多くの人にとって記事の執筆がしやすい環境を作りたいと考えています。
Qiitaのエディタの改善は続けていますが、新しい体験として「自分自身でカスタマイズした環境で記事執筆、投稿ができる」体験を提供したいと考えています。
まずはベータ版として公開し、この体験がユーザーの皆さんにとって価値があるか検証を行います。

## どのように使うか

[詳しい使い方はリポジトリのREADMEをご覧ください。](https://github.com/increments/qiita-cli)

**Comment by kyntk** [comment]
Qiita CLIをベータ版として公開しました  🚀
詳しい内容は[Qiita Blog](https://blog.qiita.com/qiita-cli-beta-release/)をご確認ください。

**Comment by getty104** [comment]
Qiita CLIを正式版として公開しました 🚀 
詳しい内容は[Qiita Blog](https://blog.qiita.com/release-qiita-cli-general/)をご確認ください。
