### ISSUE TITLE
バッジの拡充 (Contribution数の達成)

### ISSUE THREAD

**Issue by kyntk** [increments/qiita-discussions#483]
## 概要

バッジの種類の拡充を検討しています。
以前からバッジに関してはご意見をいただいておりました。
今回はContribution数の達成バッジを付与することを検討しています。

バッジ機能については Qiita ヘルプをご確認ください。

https://help.qiita.com/ja/articles/qiita-badge

## 期待される効果

現在「Qiita表彰プログラム」という形で、一定以上のContribution数に達した方を
表彰させていただいていますが、条件が高めに設定されており、喜びを得られる人数や頻度が
限られています。

今回のContribution達成バッジでは、よりコンスタントに特定のContribution数に
達成したことを賞賛・喜べるような体験を作りたいと考えています。

## どのように使うか

ユーザーの皆さまに設定いただく内容はありません。
1Contributionの達成から始まり、以降も一定のContribution数に達成したタイミングでバッジの付与を行わせていただきます。

## 関連するご意見

- https://github.com/increments/qiita-discussions/discussions/117
- https://github.com/increments/qiita-discussions/discussions/166
- https://github.com/increments/qiita-discussions/discussions/470
- https://github.com/increments/qiita-discussions/discussions/183

## 参考

- https://help.qiita.com/ja/articles/qiita-badge

**Comment by acronhub** [comment]
リリースしました :rocket:

[リリースノート](https://qiita.com/release-notes/2023-08-03)
