### ISSUE TITLE
トレンドを「個人記事」「Organization記事」で絞り込みを行えるようにする

### ISSUE THREAD

**Issue by getty104** [increments/qiita-discussions#545]
## 概要

現在のトレンドは、全てのユーザーの記事が表示されていますが、以下のように絞り込みを行うことを可能にします。

- すべて（絞り込みなし）
- 個人記事
- Oragnization記事

## 期待される効果
トレンドでの絞り込みを行えるようにすることで、読者の方が目的の記事を探しやすい形を目指します。

## どのように使うか

トレンドページで絞り込みを行えるようにする予定です。
詳しい方法についてはリリース後にご案内します。

**Comment by ohakutsu** [comment]
リリースしました 🚀 
https://qiita.com/release-notes/2023-10-04
