### ISSUE TITLE
タグ候補表示に 名寄せされたタグ も表示して欲しい

### ISSUE THREAD

**Issue by xrxoxcxox** [increments/qiita-discussions#70]
### Discussed in https://github.com/increments/qiita-discussions/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **shiracamus** November 22, 2021</sup>
タグに RubyOnRails を指定しても Rails に名寄せ（自動変更）されます。
タグ入力時、RubyOn まで入力して手を止めると、

* RubyOnRails5.2
* RubyOnRails6.0
* RubyOnRalis （←じつはスペルミスしているので指定して欲しくない）

などが候補表示され、RubyOnRails が表示されません。
そのため、RubyOnRails5.2 や スペルミスしている RubyOnRalis を指定する記事が後を絶ちません。
そこで、名寄せ登録されている RubyOnRails を先頭に表示するようにしていただけないでしょうか。
</div>

元のDiscussionの通りの内容で実装をする

**Comment by kyntk** [comment]
以下対応しました https://qiita.com/release-notes#2021-12-09
- RubyOnRalis を Railsに名寄せ
- 候補として名寄せした元のタグではなく、名寄せ先のタグを表示
