### ISSUE TITLE
検索結果画面のフォーカスについて

### ISSUE THREAD

**Issue by xrxoxcxox** [increments/qiita-discussions#98]
### Discussed in https://github.com/increments/qiita-discussions/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **cia-rana** December 26, 2021</sup>
検索結果画面（ https://qiita.com/search ）では初期フォーカスが検索ワード入力欄になっていますが、これを止めていただきたいです。

というのも、検索直後や、検索結果画面から記事ページに行って帰ってきたとき、2ページ目以降を閲覧したときに再度検索ワードを変更することは少ないからです。
さらに検索結果画面の下側にスクロールするためにキーボードの↓ボタンを押す際に、検索ワード入力欄にフォーカスが当たっているためにスクロールできない問題もあるからです。</div>

Discussionにあるとおり、デフォルトのフォーカスを外す

**Comment by ohakutsu** [comment]
こちら修正してリリースしました！

リリースノート: https://qiita.com/release-notes#2022-01-07
